version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: gureum_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gureum_network

volumes:
  mysql_data:

networks:
  gureum_network:
